export enum PaypalWebhookEventTypeEnum {
  CANCEL = 'BILLING.SUBSCRIPTION.CANCELLED',
  CREATED = 'BILLING.SUBSCRIPTION.CREATED',
  EXPIRED = 'BILLING.SUBSCRIPTION.EXPIRED',
  ACTIVATED = 'BILLING.SUBSCRIPTION.ACTIVATED',
  FAILED = 'BILLING.SUBSCRIPTION.PAYMENT.FAILED',
  SUSPENDED = 'BILLING.SUBSCRIPTION.SUSPENDED',
  UPDATED = 'BILLING.SUBSCRIPTION.UPDATED',
  RE_ACTIVATED = 'BILLING.SUBSCRIPTION.RE-ACTIVATED',
  PAYMENT_COMPLETED = 'PAYMENT.SALE.COMPLETED'
}
